-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 16:43:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_proyecto` DEFAULT CHARACTER SET utf8 ;
USE `db_proyecto` ;

-- -----------------------------------------------------
-- Table `db_proyecto`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proyecto`.`empleados` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `correo` VARCHAR(80) NULL,
  `rol` CHAR(1) NULL COMMENT 'S = Supervisor\nD = Desarrollador\nQ = QA',
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_proyecto`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proyecto`.`proyectos` (
  `id_proyecto` INT NOT NULL AUTO_INCREMENT,
  `nombre_proyecto` VARCHAR(45) NULL,
  `descripcion` VARCHAR(100) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `estado_proyecto` CHAR(1) NULL COMMENT 'P = Planeado\nI = Iniciado\nC = Completado\nX = Cancelado',
  PRIMARY KEY (`id_proyecto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_proyecto`.`proyectos_empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_proyecto`.`proyectos_empleados` (
  `id_proyectos_empleados` INT NOT NULL AUTO_INCREMENT,
  `id_empleado` INT NOT NULL,
  `id_proyecto` INT NOT NULL,
  PRIMARY KEY (`id_proyectos_empleados`),
  INDEX `fk_proyectos_empleados_empleados_idx` (`id_empleado` ASC) ,
  INDEX `fk_proyectos_empleados_proyectos1_idx` (`id_proyecto` ASC) ,
  CONSTRAINT `fk_proyectos_empleados_empleados`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `db_proyecto`.`empleados` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyectos_empleados_proyectos1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `db_proyecto`.`proyectos` (`id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
